export const cities = [
  { ar: "الإسماعيلية", en: "Ismailia" },
  { ar: "القاهرة", en: "Cairo" },
  { ar: "الإسكندرية", en: "Alexandria" },
  { ar: "الجيزة", en: "Giza" },
  { ar: "الشرقية", en: "Sharqia" },
  { ar: "الدقهلية", en: "Dakahlia" },
  { ar: "المنوفية", en: "Monufia" },
  { ar: "البحيرة", en: "Beheira" },
  { ar: "كفر الشيخ", en: "Kafr el-Sheikh" },
  { ar: "دمياط", en: "Damietta" },
  { ar: "المنصورة", en: "Mansoura" },
  { ar: "الفيوم", en: "Fayoum" },
  { ar: "بني سويف", en: "Beni Suef" },
  { ar: "السلوم", en: "Sallum" },
  { ar: "الوادي الجديد", en: "New Valley" },
  { ar: "الأقصر", en: "Luxor" },
  { ar: "أسوان", en: "Aswan" },
  { ar: "قنا", en: "Qena" },
  { ar: "سوهاج", en: "Sohag" },
  { ar: "المنيا", en: "Minya" },
  { ar: "أسيوط", en: "Assiut" },
  { ar: "بورسعيد", en: "Port Said" },
  { ar: "العريش", en: "Arish" },
  { ar: "رفح", en: "Rafah" },
  { ar: "شرم الشيخ", en: "Sharm el-Sheikh" },
  { ar: "السويس", en: "Suez" },
];
